### ISSUE TITLE
singularity should create the folder for the pid file if it doesn't exist

### ISSUE THREAD

**Issue by adregner** [alunduil/singularity#1]
This is expecially necessary on distros like the latest Ubuntu that symlink /var/run to /run, which is a tmpfs.

1 2012-09-06T17:02:02.%f+0000 singularity: ERROR => root: [Errno 2] No such file or directory: '/var/run/singularity/singularity.pid'
Traceback (most recent call last):
  File "/usr/local/bin/singularity", line 22, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/singularity/application.py", line 93, in run
    subcommands[SingularityParameters()["subcommand"]]()()
  File "/usr/local/lib/python2.7/dist-packages/singularity/daemonizer.py", line 36, in **call**
    actions[SingularityParameters()["action"]]()
  File "/usr/local/lib/python2.7/dist-packages/singularity/daemonizer.py", line 90, in start
    with context:
  File "/usr/lib/python2.7/dist-packages/daemon/daemon.py", line 352, in **enter**
    self.open()
  File "/usr/lib/python2.7/dist-packages/daemon/daemon.py", line 344, in open
    self.pidfile.**enter**()
  File "/usr/local/lib/python2.7/dist-packages/singularity/daemonizer.py", line 222, in **enter**
    self.pidfile = open(self.path, "a+")
IOError: [Errno 2] No such file or directory: '/var/run/singularity/singularity.pid'

root@singularity:~# ll -d /var/run 
lrwxrwxrwx 1 root root 4 May  1 21:49 /var/run -> /run/

root@singularity:~# mount | grep /run
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)

**Comment by alunduil** [comment]
Should we check for both the run directory and the directory containing the pidfile or assume they are the same?

**Comment by adregner** [comment]
just the "singularity" part of the path.  If they are specifying /var/run/something and /var/run doesn't even exist, then they deserve to error out.

**Comment by alunduil** [comment]
Perhaps the local package should install a modified configuration file without the /var/run/singularity/ requirement or the local package can create this directory?  I don't like making assumptions about another person's configuration or system.  I think it's appropriate for a package manager to setup sane defaults for the distribution in question.  What do you think?

**Comment by adregner** [comment]
Okay, but then singularity should default to /var/run/singularity.pid,
because that is a sane default that will work out of the box.  It should be
easy to do "python setup.py install" and make it work.  One shouldn't have
to troubleshoot through logs to figure out that they need to make a new
folder, even though they never specified anything in a configuration file
they never touched.

**Comment by alunduil** [comment]
I'd be inclined to verify the existence of the run directory with that argument.  I can certainly do that.  Then it will work out of the box and only break if they change the configuration themselves.  Does that sounds acceptable?
