### ISSUE TITLE
no documentation on available "ACTION" parameters

### ISSUE THREAD

**Issue by adregner** [alunduil/singularity#2]
I had to make a "logical guess" as to how to start the daemon since there is no init script to do it for me.

root@singularity:~# singularity daemon --help
usage: singularity daemon [-h] [--functions FUNCTIONS] [--loglevel LEVEL]
                          [--cache DIR] [--loghandler HANDLER]
                          [--configuration DIR] [--backup] [--run DIR]
                          [--uid USER] [--nodaemonize]
                          [--configurators [DIR [DIR ...]]] [--coredumps]
                          [--gid GROUP] [--pidfile FILE]
                          ACTION

An Openstack Guest Agent for Hypervisor and Guest Communication

positional arguments:
  ACTION                Specifies what action to take when controlling the
                        daemon process.

**Comment by alunduil** [comment]
Alright, I've added documentation specifying legal values for ACTION.  The patch is pasted here for review:

diff --git a/singularity/parameters/arguments.py b/singularity/parameters/arguments.py
index 9889def..b3f4946 100644
--- a/singularity/parameters/arguments.py
+++ b/singularity/parameters/arguments.py
@@ -67,9 +67,12 @@ class SingularityArguments(object):
             logger.debug("Adding option, %s, with options, %s and %s", name, options["args"], options["kwargs"]) # pylint: disable=C0301
             self._apply_parser.add_argument(_options["args"], *_options["kwargs"]) # pylint: disable=W0142,C0301
-        self._apply_parser.add_argument("action", metavar = "ACTION", nargs = "+",
-                choices = [ "all", "network", "hosts", "hostname", "resolvers", "password", "file", "update" ], # TODO Generate this somehow. # pylint: disable=C0301
-                help = "Specifies the action(s) to apply to the system.")
-        actions = [ "all", "network", "hosts", "hostname", "resolvers", "password", "file", "update" ] # TODO Generate this dynamically. # pylint: disable=C0301
-        self._apply_parser.add_argument("action", metavar = "ACTION",
-                nargs = "+", choices = actions, help = \
-                        "Specifies the action(s) to apply to the system.  " \
-                        "Legal ACTIONs are: {0}".format(", ".join(actions))
- ```
                     )
  
   self._daemon_parser = subparsers.add_parser('daemon', parents = [common],
           help = \
  ```
  
  @@ -82,9 +85,12 @@ class SingularityArguments(object):
           logger.debug("Adding option, %s, with options, %s and %s", name, options["args"], options["kwargs"]) # pylint: disable=C0301
           self._daemon_parser.add_argument(_options["args"], *_options["kwargs"]) # pylint: disable=W0142,C0301
- ```
     self._daemon_parser.add_argument("action", metavar = "ACTION", choices = [
  ```
-            "start", "stop", "restart", "reload", "status" ],
-            help = "Specifies what action to take when controlling the daemon process.") # pylint: disable=C0301
-        actions = [ "start", "stop", "restart", "reload", "status" ]
-        self._daemon_parser.add_argument("action", metavar = "ACTION",
-                choices = actions, help = \
-                        "Specifies what action to take when controlling the " \
-                        "daemon process.  Legal ACTIONs are: {0}".format(", ".join(actions))
- ```
                     )
  
   if parse:
       self._parsed_args = self._parser.parse_args()
  ```

This is commited in 06995af.
