### ISSUE TITLE
Problem on CentOS 6.3 python 2.6.6 system

### ISSUE THREAD

**Issue by phil-hopkins-a** [alunduil/singularity#4]
On a CentOS 6.3 system I ran:
LOGLEVEL=debug PYTHONPATH="." bin/singularity daemon -H /tmp/singularity.log -l debug --nodaemonize start

and got:

ERROR => console: bin/singularity:24 in main: super() argument 1 must be type, not classobj
Traceback (most recent call last):
  File "bin/singularity", line 20, in main
    app = SingularityApplication()
  File "/root/singularity/singularity/application.py", line 75, in **init**
    dhl.addFilter(LevelFilter(logging.DEBUG))
  File "/root/singularity/singularity/application.py", line 68, in **init**
    super(LevelFilter, self).**init**(_args, *_kwargs)
TypeError: super() argument 1 must be type, not classobj

**Comment by alunduil** [comment]
So I've found the following information: http://stackoverflow.com/questions/489269/python-super-raises-typeerror-why

Can I get the LevelFilter declaration from your version of python?  I'm assuming that it does not inherit from object as the article suggests which would imply that this is an upstream issue that needs to be fixed.

The other verification we can do is check the type directly:

alunduil@elijah ~ % ipython

In [1]: import inspect

In [2]: import logging

In [3]: inspect.getmro(logging.Filt
logging.Filter    logging.Filterer  

In [3]: inspect.getmro(logging.Filter)
Out[3]: (logging.Filter, object)

The last should contain object on your version as well but if not I think we've found the cause.

**Comment by phil-hopkins-a** [comment]
how is this:

---

Python 2.6.6 (r266:84292, Jun 18 2012, 14:18:47) 
Type "copyright", "credits" or "license" for more information.

IPython 0.10 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

In [1]: import inspect

In [2]: import logging

In [3]: inspect.getmro(logging.Filter)
Out[3]: (<class logging.Filter at 0x2366470>,)

**Comment by alunduil** [comment]
Ok, so that would be the issue.  Is that something that can be patched in the python version?  This is latest CentOS so I'm thinking an upstream bug.  The patch is super simple (add the object inheritance for Filter in the core logging module.  I believe that's a valid fix but the Red Hat people will have to decide that.

I have verified that if you change /usr/lib64/python2.6/logging/**init**.py so that class Filter: -> class Filter(object): then super works correctly for its children.

Let me know if we can push that fix upstream or if we need to think about working around it.

**Comment by phil-hopkins-a** [comment]
Check it one more time. I just ran an update on the server and it updated the python and python-lib packages. Maybe that will fix it. Otherwise I will look at patching python.

[X][X][X][X]
Phil Hopkins RHCA CMDBA
Red Hat Linux Instructor
Rackspace Hostingtm
(210) 312-3584
