### ISSUE TITLE
does not work: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by robbat2** [alunduil/singularity#5]
livecd singularity # singularity apply --noop  --loghandler -  all
1 2014-06-15T09:09:57.%f+0000 singularity: ERROR => root: unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/singularity", line 22, in main
    app.run()
  File "/usr/lib64/python2.7/site-packages/singularity/application.py", line 93, in run
    subcommands[SingularityParameters()["subcommand"]]()()
  File "/usr/lib64/python2.7/site-packages/singularity/applicator.py", line 40, in **call**
    logger.debug("Nothing special, using %s", set(actions))
TypeError: unhashable type: 'list'

steps to reproduce:
new rackspace image booted from boot.rackspace.com
unpack infra's stage4 (hardened stage3+cfengine)
add portage
add singularity
singularity apply --noop  --loghandler -  all
fail

**Comment by alunduil** [comment]
Well, I can honestly say this is some terrible application logic.  I think I'm going to need to reimplement the wrapper items and get rid of the daemonization capacity.  I can probably have this work finished in a week or two if it's really needed.

Let me know if I should start working on the 2.x series to fix these problems or if hacking is preferred or if this should be dropped.

Looking at it again, I think I see the problem.  I'll push something to master.  Please, let me know if it fixes the issue.  Also, can you set debug output and provide that as well if it doesn't work next time?

**Comment by alunduil** [comment]
@robbat2, if you know of people who want to use this system over cloud-init we should find out why and discuss merging the features they like into cloud-init or creating a singularity-2.x.

**Comment by alunduil** [comment]
Closing as this project is currently abandoned.
